### ISSUE TITLE
Missing "/" in GPG URL for RHEL bases OS

### ISSUE THREAD

**Issue by kanisae** [Project0/puppet-bareos#14]
When attempting to install on CentOS 7, I was getting 404 errors during the yum transaction like below:

`Error: /Stage[main]/Bareos::Client/Package[bareos-filedaemon-python-plugin]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install bareos-filedaemon-python-plugin' returned 1: warning: /var/cache/yum/x86_64/7/bareos/packages/bareos-filedaemon-17.2.4-9.1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 093bfba2: NOKEY

GPG key retrieval failed: [Errno 14] HTTP Error 404 - Not Found`

Looking into it, the URL was missing a "/" in repository.pp, here is my diff of fixing it.

`

@@ -40,7 +40,7 @@ class bareos::repository(
--
  |   | name     => 'bareos',
  |   | baseurl  => $location,
  |   | gpgcheck => '1',
  |   | -          gpgkey   => "${location}repodata/repomd.xml.key",
  |   | +          gpgkey   => "${location}/repodata/repomd.xml.key",
  |   | priority => '1',
  |   | }
  |   | }

`

**Comment by Project0** [comment]
will be fixed with #13
